version: v0.13.0

dsn: postgres://evt-app:norstarSystemsCveraBabyl0n!@db:5432/evt_kratos?sslmode=disable

log:
  level: info
  format: text

serve:
  public:
    base_url: https://auth.cvera.app
    cors:
      enabled: true
      allowed_origins:
        - https://cvera-iiw-mvp-expo-app--mvp.expo.app
        - https://mvp.cvera.app
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-CSRF-Token
        - X-Session-Token
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
    port: 4434
  admin:
    base_url: http://kratos-admin:4435
    port: 4435

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: https://mvp.cvera.app
  allowed_return_urls:
    - https://mvp.cvera.app
    - https://mvp.cvera.app/*
    - cvera://auth/callback

  flows:
    error:
      ui_url: https://mvp.cvera.app/error

    login:
      ui_url: https://mvp.cvera.app/login
      lifespan: 10m

    registration:
      ui_url: https://mvp.cvera.app/register
      lifespan: 30m

    verification:
      enabled: true
      ui_url: https://mvp.cvera.app/verify
      lifespan: 24h

    recovery:
      enabled: true
      ui_url: https://mvp.cvera.app/recovery
      lifespan: 30m

courier:
  smtp:
    connection_uri: env://KRATOS_COURIER_SMTP_CONNECTION_URI
    from_address: auth@cvera.app
    from_name: Cvera

secrets:
  default:
    - ${KRATOS_SECRET_DEFAULT}
  cookie:
    - ${KRATOS_SECRET_COOKIE}

session:
  cookie:
    domain: .cvera.app
